version: "3"

tasks:
  build:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  # check-modules runs "go mod tidy" then "go mod vendor" and exits with a non-zero exit code if there
  # are any module or vendored modules changes. The intent is to confirm two properties:
  #
  # 1. Exactly the required modules are declared as dependencies. We should always be able to run
  # "go mod tidy" and expect that no unrelated changes are made to the "go.mod" file.
  #
  # 2. All required modules are copied into the vendor/ directory and are an exact copy of the
  # original module source code (i.e. the vendored modules are not modified from their original code).
  check-modules:
    cmds:
      - go mod tidy -v
      - go mod vendor
      - git diff --exit-code go.mod go.sum ./vendor

  fmt:
    cmds:
      - go fmt ./...

  install-golangci-lint:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2

  lint:
    cmds:
      - task: install-golangci-lint
      - golangci-lint run --timeout 5m
